version: '3'
services: 
    server:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                SERVICE_NAME: server
        tty: true
        environment:
            PORT: 5000
        networks:
            - service-network
    client:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                SERVICE_NAME: client
        tty: true
        environment:
            SERVER_ADDR: server:5000
        networks:
            - service-network
networks:
    service-network:
        driver: bridge