version: '3'
services:
    client:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                SERVICE: client
        tty: true
        environment:
            SERVER_ADDR: server:7700
        networks:
            - service-network
        depends_on:
            server:
                condition: service_started
    server:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                SERVICE: server
        tty: true
        environment:
            PORT: 7700
        networks:
            - service-network
networks:
    service-network:
        driver: bridge